Repository shibam-naskar/wally, pull requests merged in 2022-02, with the labels that each got.

#9 added set as wallpaper button #2
  .gitignore
  lib/pages/home.dart
  lib/pages/singleImage.dart
  pubspec.lock
Labels: enhancement, medium, JWOC

#12 wallpaper changes on pressing OK button
  lib/pages/singleImage.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, hard, JWOC

#14 added favorites feature
  lib/main.dart
  lib/models/photo_model.dart
  lib/models/photo_model.g.dart
  lib/pages/favorites_page.dart
  lib/pages/home.dart
  lib/pages/singleImage.dart
  lib/services/network_service.dart
  lib/services/storage_service.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, hard, JWOC

#16 List of Contributors
  README.md
Labels: enhancement, good first issue, JWOC, easy

#18 adjusting wallpaper
  android/app/src/main/AndroidManifest.xml
  lib/pages/singleImage.dart
  lib/services/network_service.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, hard, JWOC

#20 Update README.md
  README.md
Labels: enhancement, good first issue, medium, JWOC

#22 Update README.md
  README.md
Labels: medium, JWOC

#23 app icon updated
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
Labels: enhancement, medium, JWOC

#24 Update README.md
  README.md
Labels: documentation, JWOC, easy
